import type { Pool } from 'pg';
import type { CashReport, CashReportCriteria, CollectionReport, CollectionReportCriteria, InstallmentReport, InstallmentReportCriteria, LoanReport, LoanReportCriteria, ReportRepository, SystemSummary } from '../domain/report-repository.js';

const page = (total: number, current: number, pageSize: number) => ({ page: current, pageSize, total, totalPages: Math.ceil(total / pageSize) });
const dateOnly = (value: Date | string): string => value instanceof Date ? value.toISOString().slice(0, 10) : value.slice(0, 10);
const LIMA_TODAY = "(NOW() AT TIME ZONE 'America/Lima')::date";

export class PostgresReportRepository implements ReportRepository {
  constructor(private readonly database: Pool) {}
  async getSummary(): Promise<SystemSummary> {
    const result = await this.database.query<{ active_customers: string; active_loans: string; total_disbursed: string; total_outstanding: string; total_collected: string; overdue_installments: string; payments_today_count: string; payments_today_amount: string; current_cash_balance: string }>(`
      WITH cash_per_session AS (SELECT cs.id, cs.opening_amount + COALESCE(SUM(cm.amount) FILTER (WHERE cm.type='income' AND cm.payment_method='cash'),0) - COALESCE(SUM(cm.amount) FILTER (WHERE cm.type='expense' AND cm.payment_method='cash'),0) - COALESCE(SUM(cm.amount) FILTER (WHERE cm.type='reversal' AND cm.payment_method='cash'),0) AS expected FROM cash_sessions cs LEFT JOIN cash_movements cm ON cm.cash_session_id=cs.id WHERE cs.status='open' GROUP BY cs.id, cs.opening_amount)
      SELECT (SELECT COUNT(*) FROM customers WHERE is_active)::text active_customers, (SELECT COUNT(*) FROM loans WHERE status='active')::text active_loans, COALESCE((SELECT SUM(principal_amount) FROM loans WHERE status <> 'cancelled'),0)::text total_disbursed, COALESCE((SELECT SUM(i.outstanding_amount) FROM installments i JOIN loans l ON l.id=i.loan_id WHERE l.status <> 'cancelled'),0)::text total_outstanding, COALESCE((SELECT SUM(amount) FROM payments WHERE status='registered'),0)::text total_collected, (SELECT COUNT(*) FROM installments i JOIN loans l ON l.id=i.loan_id WHERE l.status='active' AND i.outstanding_amount>0 AND i.due_date < ${LIMA_TODAY})::text overdue_installments, (SELECT COUNT(*) FROM payments WHERE status='registered' AND payment_date=${LIMA_TODAY})::text payments_today_count, COALESCE((SELECT SUM(amount) FROM payments WHERE status='registered' AND payment_date=${LIMA_TODAY}),0)::text payments_today_amount, COALESCE((SELECT SUM(expected) FROM cash_per_session),0)::text current_cash_balance`);
    const row = result.rows[0]!; return { activeCustomers: Number(row.active_customers), activeLoans: Number(row.active_loans), totalDisbursed: row.total_disbursed, totalOutstanding: row.total_outstanding, totalCollected: row.total_collected, overdueInstallments: Number(row.overdue_installments), paymentsToday: { count: Number(row.payments_today_count), totalAmount: row.payments_today_amount }, currentCashBalance: row.current_cash_balance };
  }
  async getLoans(criteria: LoanReportCriteria): Promise<LoanReport> {
    const values: unknown[] = []; const where: string[] = []; const add = (sql: string, value: unknown) => { values.push(value); where.push(`${sql} $${values.length}`); };
    if (criteria.fromDate) add('l.disbursement_date >=', criteria.fromDate); if (criteria.toDate) add('l.disbursement_date <=', criteria.toDate); if (criteria.customerId) add('l.customer_id =', criteria.customerId); if (criteria.status) add('l.status =', criteria.status); const condition = where.length ? `WHERE ${where.join(' AND ')}` : ''; const offset = (criteria.page - 1) * criteria.pageSize;
    const [totals, rows, count] = await Promise.all([
      this.database.query<{ loan_count: string; principal_amount: string; interest_amount: string; outstanding_amount: string; active_count: string; paid_count: string; cancelled_count: string }>(`SELECT COUNT(*)::text loan_count, COALESCE(SUM(l.principal_amount),0)::text principal_amount, COALESCE(SUM(l.total_amount-l.principal_amount),0)::text interest_amount, COALESCE(SUM(COALESCE(x.outstanding,0)),0)::text outstanding_amount, COUNT(*) FILTER (WHERE l.status='active')::text active_count, COUNT(*) FILTER (WHERE l.status='paid')::text paid_count, COUNT(*) FILTER (WHERE l.status='cancelled')::text cancelled_count FROM loans l LEFT JOIN LATERAL (SELECT SUM(outstanding_amount) outstanding FROM installments WHERE loan_id=l.id) x ON true ${condition}`, values),
      this.database.query<{ id: string; customer_id: string; customer_name: string; customer_document: string; disbursement_date: Date | string; principal_amount: string; interest_amount: string; total_amount: string; outstanding_amount: string; status: 'active'|'paid'|'cancelled' }>(`SELECT l.id,l.customer_id,concat(c.first_name,' ',c.last_name) customer_name,concat(c.document_type,' ',c.document_number) customer_document,l.disbursement_date,l.principal_amount,(l.total_amount-l.principal_amount)::text interest_amount,l.total_amount,COALESCE(SUM(i.outstanding_amount),0)::text outstanding_amount,l.status FROM loans l JOIN customers c ON c.id=l.customer_id LEFT JOIN installments i ON i.loan_id=l.id ${condition} GROUP BY l.id,c.first_name,c.last_name,c.document_type,c.document_number ORDER BY l.disbursement_date DESC,l.created_at DESC LIMIT $${values.length + 1} OFFSET $${values.length + 2}`, [...values, criteria.pageSize, offset]),
      this.database.query<{ total: string }>(`SELECT COUNT(*)::text total FROM loans l ${condition}`, values),
    ]); const totalRow = totals.rows[0]!; return { totals: { loanCount: Number(totalRow.loan_count), principalAmount: totalRow.principal_amount, interestAmount: totalRow.interest_amount, outstandingAmount: totalRow.outstanding_amount, byStatus: { active: Number(totalRow.active_count), paid: Number(totalRow.paid_count), cancelled: Number(totalRow.cancelled_count) } }, page: { items: rows.rows.map((row) => ({ id: row.id, customerId: row.customer_id, customerName: row.customer_name, customerDocument: row.customer_document, disbursementDate: dateOnly(row.disbursement_date), principalAmount: row.principal_amount, interestAmount: row.interest_amount, totalAmount: row.total_amount, outstandingAmount: row.outstanding_amount, status: row.status })), pagination: page(Number(count.rows[0]?.total ?? 0), criteria.page, criteria.pageSize) } };
  }
  async getInstallments(criteria: InstallmentReportCriteria): Promise<InstallmentReport> {
    const values: unknown[]=[]; const where: string[]=[]; const add=(sql:string,value:unknown)=>{values.push(value);where.push(`${sql} $${values.length}`);}; if(criteria.fromDate)add('i.due_date >=',criteria.fromDate); if(criteria.toDate)add('i.due_date <=',criteria.toDate); const status="CASE WHEN i.outstanding_amount=0 THEN 'paid' WHEN i.due_date < "+LIMA_TODAY+" THEN 'overdue' ELSE 'pending' END"; if(criteria.status) add(`${status} =`,criteria.status); const condition=where.length?`WHERE ${where.join(' AND ')}`:''; const offset=(criteria.page-1)*criteria.pageSize;
    const [totals,rows,count]=await Promise.all([
      this.database.query<{pending_count:string;paid_count:string;overdue_count:string;outstanding_amount:string}>(`SELECT COUNT(*) FILTER (WHERE ${status}='pending')::text pending_count,COUNT(*) FILTER (WHERE ${status}='paid')::text paid_count,COUNT(*) FILTER (WHERE ${status}='overdue')::text overdue_count,COALESCE(SUM(i.outstanding_amount),0)::text outstanding_amount FROM installments i ${condition}`,values),
      this.database.query<{id:string;loan_id:string;installment_number:number;due_date:Date|string;principal_amount:string;interest_amount:string;scheduled_amount:string;outstanding_amount:string;status:'pending'|'paid'|'overdue'}>(`SELECT i.id,i.loan_id,i.installment_number,i.due_date,i.principal_amount,i.interest_amount,i.scheduled_amount,i.outstanding_amount,${status} status FROM installments i ${condition} ORDER BY i.due_date ASC,i.installment_number ASC LIMIT $${values.length+1} OFFSET $${values.length+2}`,[...values,criteria.pageSize,offset]),
      this.database.query<{total:string}>(`SELECT COUNT(*)::text total FROM installments i ${condition}`,values),
    ]); const t=totals.rows[0]!; return { totals:{pendingCount:Number(t.pending_count),paidCount:Number(t.paid_count),overdueCount:Number(t.overdue_count),outstandingAmount:t.outstanding_amount},page:{items:rows.rows.map(row=>({id:row.id,loanId:row.loan_id,installmentNumber:row.installment_number,dueDate:dateOnly(row.due_date),principalAmount:row.principal_amount,interestAmount:row.interest_amount,scheduledAmount:row.scheduled_amount,outstandingAmount:row.outstanding_amount,status:row.status})),pagination:page(Number(count.rows[0]?.total??0),criteria.page,criteria.pageSize)}};
  }
  async getCollections(criteria: CollectionReportCriteria): Promise<CollectionReport> {
    const values:unknown[]=[];const where:string[]=["p.status = 'registered'"];const add=(sql:string,value:unknown)=>{values.push(value);where.push(`${sql} $${values.length}`);};if(criteria.fromDate)add('p.payment_date >=',criteria.fromDate);if(criteria.toDate)add('p.payment_date <=',criteria.toDate);const condition=`WHERE ${where.join(' AND ')}`;const offset=(criteria.page-1)*criteria.pageSize;
    const [total,byDay,byMethod,rows,count]=await Promise.all([
      this.database.query<{payment_count:string;total_amount:string}>(`SELECT COUNT(*)::text payment_count,COALESCE(SUM(p.amount),0)::text total_amount FROM payments p ${condition}`,values),this.database.query<{date:Date|string;payment_count:string;total_amount:string}>(`SELECT p.payment_date date,COUNT(*)::text payment_count,SUM(p.amount)::text total_amount FROM payments p ${condition} GROUP BY p.payment_date ORDER BY p.payment_date DESC`,values),this.database.query<{payment_method:string;payment_count:string;total_amount:string}>(`SELECT p.payment_method,COUNT(*)::text payment_count,SUM(p.amount)::text total_amount FROM payments p ${condition} GROUP BY p.payment_method ORDER BY p.payment_method`,values),this.database.query<{id:string;loan_id:string;installment_id:string;payment_date:Date|string;payment_method:string;amount:string;operation_reference:string|null}>(`SELECT p.id,p.loan_id,p.installment_id,p.payment_date,p.payment_method,p.amount,p.operation_reference FROM payments p ${condition} ORDER BY p.payment_date DESC,p.created_at DESC LIMIT $${values.length+1} OFFSET $${values.length+2}`,[...values,criteria.pageSize,offset]),this.database.query<{total:string}>(`SELECT COUNT(*)::text total FROM payments p ${condition}`,values),
    ]); const t=total.rows[0]!;return {totals:{paymentCount:Number(t.payment_count),totalAmount:t.total_amount,byDay:byDay.rows.map(row=>({date:dateOnly(row.date),paymentCount:Number(row.payment_count),totalAmount:row.total_amount})),byMethod:byMethod.rows.map(row=>({paymentMethod:row.payment_method,paymentCount:Number(row.payment_count),totalAmount:row.total_amount}))},page:{items:rows.rows.map(row=>({id:row.id,loanId:row.loan_id,installmentId:row.installment_id,paymentDate:dateOnly(row.payment_date),paymentMethod:row.payment_method,amount:row.amount,operationReference:row.operation_reference})),pagination:page(Number(count.rows[0]?.total??0),criteria.page,criteria.pageSize)}};
  }
  async getCash(criteria: CashReportCriteria): Promise<CashReport> {
    const values:unknown[]=[];const where:string[]=[];const add=(sql:string,value:unknown)=>{values.push(value);where.push(`${sql} $${values.length}`);};if(criteria.cashSessionId)add('cs.id =',criteria.cashSessionId);if(criteria.status)add('cs.status =',criteria.status);if(criteria.fromDate){values.push(criteria.fromDate);where.push(`cs.opened_at >= ($${values.length}::date::timestamp AT TIME ZONE 'America/Lima')`);}if(criteria.toDate){values.push(criteria.toDate);where.push(`cs.opened_at < (($${values.length}::date + 1)::timestamp AT TIME ZONE 'America/Lima')`);}const condition=where.length?`WHERE ${where.join(' AND ')}`:'';const cte=`WITH sessions AS (SELECT cs.id,cs.opened_at,cs.closed_at,cs.status,cs.opening_amount,cs.difference_amount,COALESCE(SUM(cm.amount) FILTER (WHERE cm.type='income' AND cm.payment_method='cash'),0) income,COALESCE(SUM(cm.amount) FILTER (WHERE cm.type='expense' AND cm.payment_method='cash'),0) expenses,COALESCE(SUM(cm.amount) FILTER (WHERE cm.type='reversal' AND cm.payment_method='cash'),0) reversals FROM cash_sessions cs LEFT JOIN cash_movements cm ON cm.cash_session_id=cs.id ${condition} GROUP BY cs.id)`;const offset=(criteria.page-1)*criteria.pageSize;
    const [totals,rows,count]=await Promise.all([
      this.database.query<{income:string;expenses:string;reversals:string;expected:string;difference:string}>(`${cte} SELECT COALESCE(SUM(income),0)::text income,COALESCE(SUM(expenses),0)::text expenses,COALESCE(SUM(reversals),0)::text reversals,COALESCE(SUM(opening_amount+income-expenses-reversals),0)::text expected,COALESCE(SUM(difference_amount),0)::text difference FROM sessions`,values),this.database.query<{id:string;opened_at:Date;closed_at:Date|null;status:'open'|'closed';opening_amount:string;income:string;expenses:string;reversals:string;expected:string;difference_amount:string|null}>(`${cte} SELECT id,opened_at,closed_at,status,opening_amount,income,expenses,reversals,(opening_amount+income-expenses-reversals)::text expected,difference_amount FROM sessions ORDER BY opened_at DESC LIMIT $${values.length+1} OFFSET $${values.length+2}`,[...values,criteria.pageSize,offset]),this.database.query<{total:string}>(`SELECT COUNT(*)::text total FROM cash_sessions cs ${condition}`,values),
    ]);const t=totals.rows[0]!;return {totals:{incomeAmount:t.income,expenseAmount:t.expenses,reversalAmount:t.reversals,expectedBalance:t.expected,closingDifference:t.difference},page:{items:rows.rows.map(row=>({id:row.id,openedAt:row.opened_at,closedAt:row.closed_at,status:row.status,openingAmount:row.opening_amount,incomeAmount:row.income,expenseAmount:row.expenses,reversalAmount:row.reversals,expectedBalance:row.expected,differenceAmount:row.difference_amount})),pagination:page(Number(count.rows[0]?.total??0),criteria.page,criteria.pageSize)}};
  }
}
