import { AppError, notFound } from '../../../shared/errors/app-error.js';
import { amountToCents, centsToAmount } from '../../interest/domain/monetary-value.js';
import type { CashAuditLogger } from '../domain/cash-audit-logger.js';
import type { CashMovementData } from '../domain/cash-movement.js';
import type { CashHistoryCriteria, CashRepository, CashSessionPage, CloseCashSessionInput, CreateCashMovementInput, OpenCashSessionInput } from '../domain/cash-repository.js';
import type { CashSessionData } from '../domain/cash-session.js';

const positive = (value: string | number, field: string): string => { const cents = amountToCents(value); if (cents <= 0n) throw new AppError(422, 'INVALID_CASH_AMOUNT', `El ${field} debe ser mayor que cero.`); return centsToAmount(cents); };
export class OpenCashSessionUseCase { constructor(private readonly cash: CashRepository, private readonly audit: CashAuditLogger) {} async execute(input: Omit<OpenCashSessionInput, 'openingAmount' | 'openedByUserId'> & { openingAmount: string | number }, actorId: string): Promise<CashSessionData> { const session = await this.cash.open({ openingAmount: positive(input.openingAmount, 'monto inicial'), observations: input.observations?.trim() || null, openedByUserId: actorId }); await this.audit.record('cash.opened', actorId, session.data.id); return session.data; } }
export class GetCurrentCashSessionUseCase { constructor(private readonly cash: CashRepository) {} async execute(userId: string): Promise<CashSessionData> { const session = await this.cash.findCurrentByUserId(userId); if (!session) throw new AppError(404, 'OPEN_CASH_SESSION_NOT_FOUND', 'No existe una caja abierta para el usuario actual.'); return session.data; } }
export class CreateCashMovementUseCase { constructor(private readonly cash: CashRepository, private readonly audit: CashAuditLogger) {} async execute(input: Omit<CreateCashMovementInput, 'amount' | 'createdByUserId'> & { amount: string | number }, actorId: string): Promise<CashMovementData> { const movement = await this.cash.createMovement({ ...input, amount: positive(input.amount, 'monto'), description: input.description.trim(), createdByUserId: actorId }); await this.audit.record('cash.movement_created', actorId, input.cashSessionId); return movement.data; } }
export class ListCashMovementsUseCase { constructor(private readonly cash: CashRepository) {} async execute(id: string): Promise<CashMovementData[]> { if (!(await this.cash.findById(id))) throw notFound('Caja'); return (await this.cash.findMovements(id)).map((movement) => movement.data); } }
export class CloseCashSessionUseCase { constructor(private readonly cash: CashRepository, private readonly audit: CashAuditLogger) {} async execute(id: string, input: Omit<CloseCashSessionInput, 'declaredClosingAmount' | 'closedByUserId'> & { declaredClosingAmount: string | number }, actorId: string): Promise<CashSessionData> { const session = await this.cash.close(id, { declaredClosingAmount: positive(input.declaredClosingAmount, 'monto declarado'), observations: input.observations?.trim() || null, closedByUserId: actorId }); await this.audit.record('cash.closed', actorId, session.data.id); return session.data; } }
export class ListCashHistoryUseCase { constructor(private readonly cash: CashRepository) {} async execute(criteria: CashHistoryCriteria): Promise<{ items: CashSessionData[]; pagination: Omit<CashSessionPage, 'items'> }> { const page = await this.cash.findHistory(criteria); return { items: page.items.map((item) => item.data), pagination: { total: page.total, page: page.page, pageSize: page.pageSize, totalPages: page.totalPages } }; } }
