import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MAT_DIALOG_DATA, MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { ConfirmDialogComponent } from '../../../../shared/components/confirm-dialog/confirm-dialog.component';
import type { CashMovementMethod, CashMovementPayload } from '../../models/cash.model';
export interface CashMovementFormData { type: 'income' | 'expense'; }
@Component({ selector: 'sp-cash-movement-form', imports: [ReactiveFormsModule, MatButtonModule, MatDialogModule, MatFormFieldModule, MatInputModule, MatSelectModule], templateUrl: './cash-movement-form.component.html', styleUrl: './cash-movement-form.component.scss', changeDetection: ChangeDetectionStrategy.OnPush })
export class CashMovementFormComponent { private readonly builder = inject(FormBuilder); private readonly ref = inject(MatDialogRef<CashMovementFormComponent>); private readonly dialog = inject(MatDialog); readonly data = inject<CashMovementFormData>(MAT_DIALOG_DATA); readonly methods: { value: CashMovementMethod; label: string }[] = [{ value: 'cash', label: 'Efectivo' }, { value: 'bank_transfer', label: 'Transferencia bancaria' }, { value: 'yape', label: 'Yape' }, { value: 'plin', label: 'Plin' }, { value: 'other', label: 'Otro' }]; readonly form = this.builder.nonNullable.group({ amount: [0, [Validators.required, Validators.min(0.01), Validators.pattern(/^\d+(?:\.\d{1,2})?$/)]], paymentMethod: ['cash' as CashMovementMethod, Validators.required], description: ['', [Validators.required, Validators.minLength(3), Validators.maxLength(500)]] }); get isExpense(): boolean { return this.data.type === 'expense'; } save(): void { if (this.form.invalid) { this.form.markAllAsTouched(); return; } const value = this.form.getRawValue(); const payload: CashMovementPayload = { amount: Number(value.amount), paymentMethod: value.paymentMethod, description: value.description.trim() }; if (!this.isExpense) { this.ref.close(payload); return; } this.dialog.open(ConfirmDialogComponent, { data: { title: 'Registrar egreso', message: `¿Confirmas el egreso de S/ ${payload.amount.toFixed(2)}?`, confirmLabel: 'Registrar egreso' } }).afterClosed().subscribe((confirmed: boolean | undefined) => { if (confirmed) this.ref.close(payload); }); } }
