import { AppError } from '../../src/shared/errors/app-error.js';
import { GetCashReportUseCase, GetCollectionReportUseCase, GetInstallmentReportUseCase, GetLoanReportUseCase, GetSystemSummaryUseCase } from '../../src/modules/reports/application/report.use-cases.js';
import type { ReportRepository } from '../../src/modules/reports/domain/report-repository.js';

describe('casos de uso de reportes', () => {
  const reports: ReportRepository = { getSummary: jest.fn(), getLoans: jest.fn(), getInstallments: jest.fn(), getCollections: jest.fn(), getCash: jest.fn() };
  beforeEach(() => jest.clearAllMocks());
  it('devuelve el resumen agregado sin modificar información', async () => { (reports.getSummary as jest.Mock).mockResolvedValue({ activeCustomers: 2, activeLoans: 1, totalDisbursed: '100.00', totalOutstanding: '50.00', totalCollected: '50.00', overdueInstallments: 0, paymentsToday: { count: 1, totalAmount: '10.00' }, currentCashBalance: '20.00' }); await expect(new GetSystemSummaryUseCase(reports).execute()).resolves.toMatchObject({ totalOutstanding: '50.00', paymentsToday: { count: 1 } }); });
  it('propaga filtros y paginación de cartera', async () => { (reports.getLoans as jest.Mock).mockResolvedValue({ totals: { loanCount: 0 }, page: { items: [], pagination: { page: 2, pageSize: 10, total: 0, totalPages: 0 } } }); await new GetLoanReportUseCase(reports).execute({ page: 2, pageSize: 10, status: 'active', fromDate: '2026-01-01', toDate: '2026-01-31' }); expect(reports.getLoans).toHaveBeenCalledWith(expect.objectContaining({ status: 'active', page: 2 })); });
  it.each(['loans', 'installments', 'collections', 'cash'] as const)('rechaza un rango inválido para %s', async (report) => { const criteria = { page: 1, pageSize: 20, fromDate: '2026-02-02', toDate: '2026-02-01' }; const useCase = report === 'loans' ? new GetLoanReportUseCase(reports) : report === 'installments' ? new GetInstallmentReportUseCase(reports) : report === 'collections' ? new GetCollectionReportUseCase(reports) : new GetCashReportUseCase(reports); await expect(useCase.execute(criteria)).rejects.toMatchObject<AppError>({ code: 'INVALID_DATE_RANGE' }); });
  it('mantiene resultados vacíos y totales calculados del repositorio', async () => { (reports.getInstallments as jest.Mock).mockResolvedValue({ totals: { pendingCount: 0, paidCount: 0, overdueCount: 0, outstandingAmount: '0.00' }, page: { items: [], pagination: { page: 1, pageSize: 20, total: 0, totalPages: 0 } } }); await expect(new GetInstallmentReportUseCase(reports).execute({ page: 1, pageSize: 20 })).resolves.toMatchObject({ totals: { outstandingAmount: '0.00' }, page: { items: [] } }); });
});
